name: Release
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - master
      - next
      - release
      - '*.x'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_SEMVER_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 'lts/*'
      - run: yarn
      - run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_SEMVER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_DEVOPS_WEBHOOK: ${{ secrets.SLACK_DEVOPS_WEBHOOK }}
